project:
  type: website
  output-dir: docs

website:
  title: "DATA661 2022 Fall"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - schedule.qmd
      - resources.qmd
    right:
      - icon: twitter
        href: https://twitter.com/jbryer
      - icon: github
        menu:
          - text: Course Repo
            href: https://github.com/jbryer/DATA661Fall2022
          - text: mldash Repo
            href: https://github.com/jbryer/mldash
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

