---
title: "Resources"
editor_options: 
  chunk_output_type: console
editor: source
website:
  page-navigation: false
---


### References Materials

This is a list of books that will be helpful to reference throughout the semester to build the R package.

[Happy Git and Github for the useR](Happy Git and GitHub for the useR) by Jenny Bryan

[R for Data Science](https://r4ds.had.co.nz) by Hadley Wickham and Garrett Grolemund

[Advanced R](https://adv-r.hadley.nz) by Hadley Wickham

[R Packages](https://r-pkgs.org) by Hadley Wickham

[Mastering Shiny](https://mastering-shiny.org) by Hadley Wickham

### Install rJava

Note that I believe we need to install Java version 1.8.x. I have included some articles to install rJava for various platforms.

* [Mac OS](https://zhiyzuo.github.io/installation-rJava/)
* [Ubuntu](https://datawookie.netlify.com/blog/2018/02/installing-rjava-on-ubuntu/)
* [Windows](https://cimentadaj.github.io/blog/2018-05-25-installing-rjava-on-windows-10/installing-rjava-on-windows-10/)

### Datasets

We want to focus on these repositories of datasets, but if you find other interesting datasets elsewhere (e.g. Kaggle) feel free to add them.

* [UCI Machine Learning Repository](https://archive.ics.uci.edu/ml/index.php). See also the [`ucimlr` R package](https://github.com/tyluRp/ucimlr) as they have already done some of the data cleaning and processing.

* [OpenML](https://www.openml.org) is platform for sharing machine learning datasets and algorithms. Our goals are slightly different than theirs, but we should explore what they have to offer. Here are materials from a tutoral given at useR! 2017: https://github.com/openml/articles/tree/master/slides/useR2017_tutorial



### References

We'll add to this list references about the machine learning algorithms and datasets used in the package.

Fernández-Delgado, M., Cernadas, E., Barro, S., & Amorim, D. (2014). [Do we Need Hundreds of Classifiers to Solve Real World Classification Problems?](https://jmlr.org/papers/v15/delgado14a.html), *Journal of Machine Learning Research 15*.

